POST http://localhost:8000/signin
Content-Type: application/json

{
    "id": "1005",
    "password": "123"
}
###


POST http://localhost:8000/signup
Content-Type: application/json

{
    "id": "1006",
    "password": "123"
}
###


GET http://localhost:8000/info
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxMDA2IiwiaWF0IjoxNjAwMjQwNjc1LCJleHAiOjE2MDAyNDEyNzV9.qEc2tfeze82EK0fQXf2UAye5mmQNvKy_rZcV8bALNKs
###

POST http://localhost:8000/signin/new_token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxMDA1IiwiaWF0IjoxNjAwMjQwMTM5LCJleHAiOjE2MDI4MzIxMzl9.DyV7QlGQjp6D844KgG2Fk_t7fEhKwHL5ar8gcHQm6KI"
}
###


GET  http://localhost:8000/logout
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxMDA1IiwiaWF0IjoxNjAwMjQwNjMyLCJleHAiOjE2MDAyNDEyMzJ9.3xgC4W4U6YPsIn-Cg2qvsOxfZKX2JM9V39zkZoHIWBw;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxMDA1IiwiaWF0IjoxNjAwMjQwNjMyLCJleHAiOjE2MDI4MzI2MzJ9.zKPPPjKJ4oJm4uorRr1Oq_VH6Ldk_sB3GAgWaq5T7VY
###


// ----------------------------------------------------


GET http://localhost:8000/file/list
###


